eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
    
spring:
  config:
    import: optional:configserver:http://localhost:8888  
      
management:
  tracing:
    sampling:
      probability: 1.0